-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.bookmarks
(
    user_id integer NOT NULL,
    fanfic_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT bookmarks_pkey PRIMARY KEY (user_id, fanfic_id)
);

CREATE TABLE IF NOT EXISTS public.chapters
(
    id integer NOT NULL DEFAULT nextval('chapters_id_seq'::regclass),
    fanfic_id integer NOT NULL,
    title character varying(255) COLLATE pg_catalog."default",
    content text COLLATE pg_catalog."default" NOT NULL,
    "position" integer NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT chapters_pkey PRIMARY KEY (id),
    CONSTRAINT chapters_fanfic_id_position_key UNIQUE (fanfic_id, "position")
);

CREATE TABLE IF NOT EXISTS public.comments
(
    id integer NOT NULL DEFAULT nextval('comments_id_seq'::regclass),
    user_id integer NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    chapter_id integer,
    CONSTRAINT comments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.fanfics
(
    id integer NOT NULL DEFAULT nextval('fanfics_id_seq'::regclass),
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    summary text COLLATE pg_catalog."default",
    language character varying(50) COLLATE pg_catalog."default",
    image_url text COLLATE pg_catalog."default",
    words_count integer,
    rating character varying(20) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default",
    warnings character varying(50) COLLATE pg_catalog."default",
    author_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    pages integer GENERATED ALWAYS AS (ceiling(((COALESCE(words_count, 0))::numeric / 250.0))) STORED,
    relationship relationship_category NOT NULL DEFAULT 'Gen'::relationship_category,
    ao3_id character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    cluster character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT fanfics_pkey PRIMARY KEY (id),
    CONSTRAINT unique_ao3_id UNIQUE (ao3_id)
);

CREATE TABLE IF NOT EXISTS public.fanfics_tags
(
    fanfic_id integer NOT NULL,
    tag_id integer NOT NULL,
    CONSTRAINT fanfics_tags_pkey PRIMARY KEY (fanfic_id, tag_id)
);

CREATE TABLE IF NOT EXISTS public.likes
(
    user_id integer NOT NULL,
    fanfic_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT likes_pkey PRIMARY KEY (user_id, fanfic_id)
);

CREATE TABLE IF NOT EXISTS public.reading_history
(
    user_id integer NOT NULL,
    fanfic_id integer NOT NULL,
    chapter_id integer,
    read_time integer,
    last_read_at timestamp with time zone DEFAULT now(),
    CONSTRAINT reading_history_pkey PRIMARY KEY (user_id, fanfic_id)
);

CREATE TABLE IF NOT EXISTS public.tags
(
    id integer NOT NULL DEFAULT nextval('tags_id_seq'::regclass),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    type character varying(20) COLLATE pg_catalog."default",
    relationship_type relationship_type,
    CONSTRAINT tags_pkey PRIMARY KEY (id),
    CONSTRAINT tags_name_type_unique UNIQUE (name, type)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL DEFAULT nextval('users_id_seq'::regclass),
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    avatar_url text COLLATE pg_catalog."default",
    bio text COLLATE pg_catalog."default",
    is_admin boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    preference_cluster character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_username_key UNIQUE (username)
);

ALTER TABLE IF EXISTS public.bookmarks
    ADD CONSTRAINT bookmarks_fanfic_id_fkey FOREIGN KEY (fanfic_id)
        REFERENCES public.fanfics (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.bookmarks
    ADD CONSTRAINT bookmarks_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_bookmarks_user
    ON public.bookmarks(user_id);


ALTER TABLE IF EXISTS public.chapters
    ADD CONSTRAINT chapters_fanfic_id_fkey FOREIGN KEY (fanfic_id)
        REFERENCES public.fanfics (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_chapters_fanfic
    ON public.chapters(fanfic_id);


ALTER TABLE IF EXISTS public.comments
    ADD CONSTRAINT comments_chapter_id_fkey FOREIGN KEY (chapter_id)
        REFERENCES public.chapters (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.comments
    ADD CONSTRAINT comments_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_comments_user
    ON public.comments(user_id);


ALTER TABLE IF EXISTS public.fanfics
    ADD CONSTRAINT fanfics_author_id_fkey FOREIGN KEY (author_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_fanfics_author
    ON public.fanfics(author_id);


ALTER TABLE IF EXISTS public.fanfics_tags
    ADD CONSTRAINT fanfics_tags_fanfic_id_fkey FOREIGN KEY (fanfic_id)
        REFERENCES public.fanfics (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_fanfics_tags_fanfic
    ON public.fanfics_tags(fanfic_id);


ALTER TABLE IF EXISTS public.fanfics_tags
    ADD CONSTRAINT fanfics_tags_tag_id_fkey FOREIGN KEY (tag_id)
        REFERENCES public.tags (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_fanfics_tags_tag
    ON public.fanfics_tags(tag_id);


ALTER TABLE IF EXISTS public.likes
    ADD CONSTRAINT likes_fanfic_id_fkey FOREIGN KEY (fanfic_id)
        REFERENCES public.fanfics (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_likes_fanfic_id
    ON public.likes(fanfic_id);


ALTER TABLE IF EXISTS public.likes
    ADD CONSTRAINT likes_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_likes_user
    ON public.likes(user_id);


ALTER TABLE IF EXISTS public.reading_history
    ADD CONSTRAINT reading_history_chapter_id_fkey FOREIGN KEY (chapter_id)
        REFERENCES public.chapters (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.reading_history
    ADD CONSTRAINT reading_history_fanfic_id_fkey FOREIGN KEY (fanfic_id)
        REFERENCES public.fanfics (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_reading_history_fanfic
    ON public.reading_history(fanfic_id);


ALTER TABLE IF EXISTS public.reading_history
    ADD CONSTRAINT reading_history_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_reading_history_user
    ON public.reading_history(user_id);

END;